version: 2

jobs:
  build:
    docker:
    - image: cn007b/go:1.13

    working_directory: /go/src/github.com/thepkg/rest

    steps:
    - checkout

    - run: go get -v -t -d ./...

    - run: go vet
    - run: go fmt ./...
    - run: golint ./...
    - run: gosec -tests ./...
